initial project structure
EpamLifeSciencesTeam/cmwl_pipeline pull request #1
Opened 2019-09-15 21:40 UTC by myazinn

2019-09-16 16:04 UTC, DenisVerkhoturov requested changes
Could you, please, rename you commit message corresponding to [this guide](https://udacity.github.io/git-styleguide/).

2019-09-16 20:19 UTC, DenisVerkhoturov approved these changes

2019-09-17 14:12 UTC, Mikhail-Sosnin commented
Could you please change target branch to develop?

2019-09-17 14:17 UTC, myazinn commented
@Mikhail-Sosnin 
Done

2019-09-17 18:13 UTC, closed without merging