EPMLSTRCMW-181: Wrong response message after attempt creating existing user
EpamLifeSciencesTeam/cmwl_pipeline pull request #103
Opened 2020-09-17 07:58 UTC by Dmitrii-Shevchenko

2020-09-18 09:43 UTC, OstapStrashevskii requested changes
Useful PR! Should you pay attention to my comments?

2020-09-18 09:43 UTC, OstapStrashevskii commented on services/src/main/scala/cromwell/pipeline/service/AuthService.scala
> +      case Some(_) => Future.failed(new RuntimeException(s"${request.email} already exists"))
Why don't you make any custom Exception? There will be several Exceptions invoked by different authorization errors

2020-09-18 09:43 UTC, OstapStrashevskii commented on services/src/test/scala/cromwell/pipeline/service/AuthServiceTest.scala
> +        authService.signUp(signUpRequest).failed.map(e => e.getMessage shouldBe s"${user.email} already exists")
you should replace it with whenready ;)

2020-09-18 10:02 UTC, GrigoriiBerezin commented on services/src/main/scala/cromwell/pipeline/service/AuthService.scala
> +      case Some(_) => Future.failed(new RuntimeException(s"${request.email} already exists"))
I agree with Ostap

2020-09-21 06:44 UTC, ilyaonishenko commented
Conflicts.

2020-09-30 09:41 UTC, Dmitrii-Shevchenko commented on services/src/test/scala/cromwell/pipeline/service/AuthServiceTest.scala
> +        authService.signUp(signUpRequest).failed.map(e => e.getMessage shouldBe s"${user.email} already exists")
Done

2020-09-30 09:41 UTC, Dmitrii-Shevchenko commented on services/src/main/scala/cromwell/pipeline/service/AuthService.scala
> +      case Some(_) => Future.failed(new RuntimeException(s"${request.email} already exists"))
Done

2020-09-30 11:21 UTC, GrigoriiBerezin approved these changes
Nice

2020-10-01 10:39 UTC, IaroslavTavchenkov approved these changes
Seems clean and nice!
Thanks for you job!)

2020-10-13 09:49 UTC, mnesvit approved these changes

2020-10-15 09:33 UTC, myazinn approved these changes

2020-10-15 10:01 UTC, merged