WIP: EPMLSTRCMW-130: Marshallers tests
EpamLifeSciencesTeam/cmwl_pipeline pull request #104
Opened 2020-09-28 06:39 UTC by GrigoriiBerezin

We're widely using marshallers in controller
layer but we don't have tests which show us
which json we're getting eventually. As
following, sometimes we might run into an
issue that our understanding of output
entities will be different from what it is
really is.

2020-09-28 06:55 UTC, IaroslavTavchenkov commented
Good idea! Very curious!

2020-09-30 15:07 UTC, Dmitrii-Shevchenko approved these changes
I didn't understand anything but very interesting

2020-11-16 10:22 UTC, myazinn requested changes
You did a great job, thanks! Here are some comments on how it can be improved.

2020-11-16 10:22 UTC, myazinn commented on model/src/main/scala/cromwell/pipeline/model/wrapper/VersionValue.scala
> +  def random: VersionValue = new VersionValue(Math.abs(Random.nextInt()))
I doubt that anyone will ever need to create a random version other than in tests because it doesn't make any sense. Unlike `UserId`, for example, random version is not the part of our business logic.
UPD. turns out we don't need this method in tests too. It can be replaced with a generator.

2020-11-16 10:22 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/MarshallerTests.scala
> +        parseResult should equal(a)
Thumbs up for ScalaCheck.
However, instead of throwing an exception in test, you must fail the test. For example, you can do this
```suggestion
        val parseResult: Option[UserUpdateRequest] = userUpdateRequestFormat.reads(userUpdateRequestFormat.writes(a)).asOpt
        parseResult should equal(Some(a))
```
Alternatively 
```suggestion
        val parseResult: UserUpdateRequest = userUpdateRequestFormat.reads(userUpdateRequestFormat.writes(a)) match {
          case JsSuccess(value, _) => value
          case JsError(_)          => fail("Could not parse request")
        }
        parseResult should equal(a)
```
Note that `fail` also throws an exception, but this is a special one and it is handled by scalatest.

2020-11-16 10:22 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/FormatUtils.scala
> +object FormatUtils {
We already have formatters for all of these classes, why are they redefined here?

2020-11-16 10:22 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/GeneratorUtils.scala
> +    new PipelineVersion(VersionValue.random, VersionValue.random, VersionValue.random)
No need in implicit conversions nor `VersionValue.random` method at all.
```suggestion
  private lazy val versionValueGen: Gen[VersionValue] = Gen.posNum[Int].map(VersionValue(_, Enable.Unsafe))

  private lazy val pipelineVersionGen: Gen[PipelineVersion] =
    for {
      major <- versionValueGen
      minor <- versionValueGen
      revision <- versionValueGen
    } yield PipelineVersion(major, minor, revision)
```

2020-11-16 10:22 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/GeneratorUtils.scala
> +  private def optionGen[T](gen: Gen[T]): Gen[Option[T]] = gen.flatMap(Gen.option(_))
`Gen.option(gen)` ?

2020-11-16 10:22 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/GeneratorUtils.scala
> +  } yield Project(projectId, UserId.random, name, active, repository, visibility)
Use generator for `UserId` too.

2020-11-16 10:22 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/GeneratorUtils.scala
> +  private lazy val booleanGen: Gen[Boolean] = Gen.oneOf(List(false, true))
:(

2020-11-16 14:10 UTC, GrigoriiBerezin commented on model/src/main/scala/cromwell/pipeline/model/wrapper/VersionValue.scala
> +  def random: VersionValue = new VersionValue(Math.abs(Random.nextInt()))
Yes, thank you for notice that

2020-11-16 14:10 UTC, GrigoriiBerezin commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/MarshallerTests.scala
> +        parseResult should equal(a)
Fixed, thanks

2020-11-16 14:11 UTC, GrigoriiBerezin commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/FormatUtils.scala
> +object FormatUtils {
Yep, changed it

2020-11-16 14:15 UTC, GrigoriiBerezin commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/GeneratorUtils.scala
> +    new PipelineVersion(VersionValue.random, VersionValue.random, VersionValue.random)
Fixed, thanks

2020-11-16 14:16 UTC, GrigoriiBerezin commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/GeneratorUtils.scala
> +  private def optionGen[T](gen: Gen[T]): Gen[Option[T]] = gen.flatMap(Gen.option(_))
Yep

2020-11-17 10:55 UTC, myazinn approved these changes
Nice, thanks! There is only one minor thing left

2020-11-17 10:55 UTC, myazinn commented on model/src/main/scala/cromwell/pipeline/model/wrapper/VersionValue.scala
> +
remove it

2020-11-17 10:55 UTC, myazinn commented on repositories/src/test/scala/cromwell/pipeline/datastorage/dao/repository/utils/FormatUtils.scala
> +object FormatUtils {
I'm not sure that this class is required at all but I guess it won't do any harm either.

2020-11-19 11:57 UTC, GrigoriiBerezin commented on model/src/main/scala/cromwell/pipeline/model/wrapper/VersionValue.scala
> +
Done

2020-11-19 14:27 UTC, mnesvit approved these changes

2020-11-19 14:27 UTC, merged