EPMLSTRCMW-187
EpamLifeSciencesTeam/cmwl_pipeline pull request #109
Opened 2020-10-23 10:38 UTC by Phoenix100101

2020-10-25 23:59 UTC, alesavin reviewed
If we have to mark all tests inside GitLabProjectVersioningTest could we use "tag all tests in an entire class" feature http://doc.scalatest.org/3.0.1-2.12/org/scalatest/Tag.html ?

2020-10-25 23:59 UTC, alesavin commented on services/src/test/scala/cromwell/pipeline/service/GitLabProjectVersioningTest.scala
>            Future.successful(
Should we change tests at getFilesTree as well?

2020-10-30 22:46 UTC, alesavin commented on services/src/test/scala/cromwell/pipeline/service/GitLabProjectVersioningTest.scala
> +      "throw new VersioningException for inactive project" taggedAs Service  in {
I think it is better to remove this excessive space and have not change in line

2020-10-30 22:50 UTC, alesavin commented
Travis failed, this is expected?

[error] (services / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 73 s (01:13), completed Oct 30, 2020, 6:44:09 AM

2020-11-02 23:16 UTC, alesavin commented
I see at travis run we still run

[info] GitLabProjectVersioningTest:
[info] GitLabProjectVersioning
[info]   when createRepository
[info]   - should throw new VersioningException for inactive project

We have to exclude test at travis job config by "-l" 
https://www.scalatest.org/user_guide/using_scalatest_with_sbt

2020-11-03 09:28 UTC, myazinn approved these changes
LGTM

2020-11-03 09:29 UTC, myazinn commented on services/src/test/scala/cromwell/pipeline/service/GitLabProjectVersioningTest.scala
> +import cromwell.pipeline.utils.{AkkaTestSources, ApplicationConfig, GitLabConfig, HttpStatusCodes}
Don't forget to reformat code

2020-11-03 09:31 UTC, myazinn requested changes

2020-11-03 09:31 UTC, myazinn commented on utils/src/test/scala/cromwell/pipeline/utils/tags/ScheduledResource.scala
> +object ScheduledResource extends Tag("cromwell.pipeline.utils.tags.annotations.ScheduledResource")
I guess this is not required anymore.

2020-11-09 21:22 UTC, alesavin commented
Let rebase after #120, hope all will be fine then

2020-11-12 10:12 UTC, myazinn reviewed
Something in this PR broke coverage checks. I'm not sure, but maybe the following suggestions will fix it.

2020-11-12 10:12 UTC, myazinn commented on .travis.yml
> +- sbt "testOnly -- -l cromwell.pipeline.utils.tags.annotaions.ScheduledResource"
```suggestion
- sbt coverage "testOnly -- -l cromwell.pipeline.utils.tags.annotaions.ScheduledResource"
```

2020-11-12 10:12 UTC, myazinn commented on .travis.yml
> +- sbt coverage it:test
```suggestion
- sbt coverage it:test
- sbt coverageAggregate
```

2020-11-16 09:22 UTC, myazinn requested changes
All checks are back again which is great! However, I've noticed that tests from `GitLabProjectVersioningTest` are still run on Travis. This is probably due to a typo.

2020-11-16 09:22 UTC, myazinn commented on .travis.yml
> +- sbt coverage "testOnly -- -l cromwell.pipeline.utils.tags.annotaions.ScheduledResource"
```suggestion
- sbt coverage "testOnly -- -l cromwell.pipeline.utils.tags.annotations.ScheduledResource"
```

2020-11-16 09:22 UTC, myazinn commented on README.md
> +testOnly -- -l cromwell.pipeline.utils.tags.annotaions.ScheduledResource
```suggestion
testOnly -- -l cromwell.pipeline.utils.tags.annotations.ScheduledResource
```

2021-04-27 09:09 UTC, ilyaonishenko commented
This PR is out of date. Closing it.

2021-04-27 09:09 UTC, closed without merging