feat: EPMLSTRCMW-192 Add doc to upload file in Pipeline
EpamLifeSciencesTeam/cmwl_pipeline pull request #137
Opened 2021-03-09 10:29 UTC by eshenko

2021-03-18 16:47 UTC, egor-ka approved these changes

2021-03-22 11:18 UTC, myazinn requested changes

2021-03-22 11:18 UTC, myazinn commented on README.md
> +    },
*does not require changes*
Don't forget to update it once another your MR is merged

2021-03-22 11:18 UTC, myazinn commented on README.md
> +To add configuration to MongoDB send PUT request <br>
```suggestion
### Step 5: Add configuration
To add configuration to your Project send PUT request <br>
```
Do not share implementation details in manuals

2021-03-24 15:33 UTC, closed without merging