EPMLSTRCMW-222
EpamLifeSciencesTeam/cmwl_pipeline pull request #162
Opened 2021-05-13 19:23 UTC by OlegKoshelev

Migrated from coveralls to codecove.
- cmwl.pipeline_ci.yml has been updated

2021-05-14 07:49 UTC, gominasian approved these changes
Everything is clear for me. Approved

2021-05-14 08:11 UTC, DruzhininPavel approved these changes
Looks good.

2021-05-14 09:45 UTC, myazinn requested changes
Integration with `Codecov` doesn't seem to work. I don't see test coverage information in pull request info and there is 404 error in `build` pipeline during test data upload to `codecov` (although I surprised that build didn't fail).
Maybe if you use GitHub action then it will be resolved automatically.

2021-05-14 09:45 UTC, myazinn commented on .github/workflows/cmwl_pipeline_ci.yml
> +        run: bash <(curl -s https://codecov.io/bash)
There should be GitHub action for integration with `codecov`. Let's use it instead of raw bash command.

2021-05-14 09:45 UTC, myazinn commented on .github/workflows/cmwl_pipeline_ci.yml
> -        run: sbt coverageAggregate coveralls
We should remove `coveralls` sbt plugin since we don't need it anymore.

2021-05-26 11:55 UTC, Nikolai-Isaev approved these changes
If it works it works )

2021-05-26 23:18 UTC, ilyaonishenko approved these changes
I think commits in this MR could squashed without loosing important info.

Regarding MR, I guess we need to merge it to master and check if codecov accepts this changes. 
@myazinn  please remove you rejection (or approve).
@GrigoriiBerezin, @Dmitrii-Shevchenko please take a look.

2021-05-27 07:31 UTC, myazinn approved these changes

2021-05-27 07:43 UTC, OlegKoshelev commented
> I think commits in this MR could squashed without losing important info.
> 
> Regarding MR, I guess we need to merge it to master and check if codecov accepts these changes.
> @myazinn please remove you rejection (or approve).
> @GrigoriiBerezin, @Dmitrii-Shevchenko please take a look.

@ilyaonishenko I've squashed commits

2021-05-27 10:45 UTC, merged