EPMLSTRCMW-300 Make filters reusable
EpamLifeSciencesTeam/cmwl_pipeline pull request #231
Opened 2021-12-07 01:51 UTC by Nikolai-Isaev

feat: Make search filters reusable

- Added project_search pg table
- Added ProjectSearchRepository, corresponding ProjectSearchFilterService
- New service class ProjectSearchEngine containing search filter processing logic
was separated from ProjectSearchService
- ProjectSearchController now supports fetching search results both by new filter
and by search id

2021-12-09 09:22 UTC, DruzhininPavel approved these changes
Looks good. I don't see anything critical :)

2021-12-27 18:48 UTC, myazinn requested changes

2021-12-27 18:48 UTC, myazinn commented on datasource/src/main/resources/liquibase/changelog/changelog-0.1.xml
> +            <column name="project_search_filter_id" type="${uuid.type}"/>
names seems redundant, `project_search_filter_id` or just `id` is enough.
same for `project_search_query`.

2021-12-27 18:48 UTC, myazinn commented on datasource/src/main/resources/liquibase/changelog/changelog-0.1.xml
> +            <column name="project_search_query" type="${text.type}"/>
Why is it a text? If you want to store it as a JSON, then choose an appropriate data type. Modern databases (including postgres) support json out of the box.

2021-12-27 18:48 UTC, myazinn commented on portal/src/it/resources/application.conf
> +misc {
I find it weird that direct app configuartion is put to `misc`. IMO, `misc` is usually used for minor things that are too small to have their own section / directory / whatever. Why not call it `app` or `service` ? I could be wrong though, @ilyaonishenko what do you think?

2021-12-27 18:48 UTC, myazinn commented on portal/src/it/resources/application.conf
> +    }
When you are giving a name to something, try to give information about what it's doing in terms of high-level language. It's obvious that you are talking about durations here (because of `seconds`), so the name is not very useful IMO. It's not so obvious what filters will do with these durations.
```suggestion
    filtersCleanup {
        timeToLive = 2 seconds
        interval = 1 seconds
    }
```

2021-12-27 18:48 UTC, myazinn commented on portal/src/main/resources/application.conf
> +}
Same comment about sub-config names

2021-12-27 18:48 UTC, myazinn commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dao/entry/ProjectSearchEntry.scala
> +  def deleteOldSearches(usedLaterThan: Instant): ActionResult[Int] =
```suggestion
  def deleteOldFilters(usedLaterThan: Instant): ActionResult[Int] =
```
?

2021-12-27 18:48 UTC, myazinn commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dao/entry/ProjectSearchEntry.scala
> +  val projectSearches = TableQuery[ProjectSearchFilterTable]
Why are you calling everything `searches`, if the main entity here is `filter`, not `search`?

2021-12-27 18:48 UTC, myazinn commented on services/src/main/scala/cromwell/pipeline/service/ProjectSearchFilterCleaner.scala
> +        val _ = system.scheduler.scheduleAtFixedRate(cleanInterval, cleanInterval, getFiltersCleanRun, executionContext)
I don't see why you would need this `val` definition if it's an only line
```suggestion
        system.scheduler.scheduleAtFixedRate(cleanInterval, cleanInterval, getFiltersCleanRun, executionContext)
```

2021-12-27 18:48 UTC, myazinn commented on services/src/main/scala/cromwell/pipeline/service/ProjectSearchFilterCleaner.scala
> +  def apply(projectSearchFilterService: ProjectSearchFilterService, miscConfig: MiscConfig, system: ActorSystem)(
Why does it need a whole `MiscConfig`? Wouldn't `FiltersDuration` be enough?

2021-12-27 18:48 UTC, myazinn commented on services/src/main/scala/cromwell/pipeline/service/ProjectSearchFilterCleaner.scala
> +  def cleanExpiredFilters(): Unit
I think `scheduleFiltersCleanup` / `scheduleExpiredFiltersCleanup` would be better here since `cleanExpiredFilters` sounds like it's going to happen only once.

2021-12-27 18:48 UTC, myazinn commented on services/src/test/scala/cromwell/pipeline/service/impls/ProjectSearchFilterServiceTestImpl.scala
> +    }
Why would addition of the new entity return an exception if there are no predefined filters?

2021-12-27 18:48 UTC, myazinn commented on utils/src/test/scala/cromwell/pipeline/utils/configs/ConfigJsonOpsTest.scala
> +       |      }
Why are you still using it?

2021-12-27 18:48 UTC, myazinn commented on controllers/src/test/scala/cromwell/pipeline/controller/ProjectSearchControllerTest.scala
> +      "Return 404 if no projects was found" in {
If no projects was found, we should just return an empty list as with search by the new query.

2021-12-27 18:48 UTC, myazinn commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dao/repository/ProjectSearchFilterRepository.scala
> +        database.run(projectSearchEntry.deleteOldSearches(usedLaterThan))
Same comment about `filters` vs `searches`

2022-01-09 17:16 UTC, Nikolai-Isaev commented on datasource/src/main/resources/liquibase/changelog/changelog-0.1.xml
> +            <column name="project_search_filter_id" type="${uuid.type}"/>
fixed

2022-01-09 17:17 UTC, Nikolai-Isaev commented on datasource/src/main/resources/liquibase/changelog/changelog-0.1.xml
> +            <column name="project_search_query" type="${text.type}"/>
Not fixed yet

2022-01-09 17:17 UTC, Nikolai-Isaev commented on portal/src/it/resources/application.conf
> +    }
fixed

2022-01-09 17:17 UTC, Nikolai-Isaev commented on portal/src/main/resources/application.conf
> +}
fixed

2022-01-09 17:18 UTC, Nikolai-Isaev commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dao/entry/ProjectSearchEntry.scala
> +  def deleteOldSearches(usedLaterThan: Instant): ActionResult[Int] =
fixed

2022-01-09 17:20 UTC, Nikolai-Isaev commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dao/entry/ProjectSearchEntry.scala
> +  val projectSearches = TableQuery[ProjectSearchFilterTable]
Thanks, had to rename searches to filters, some names was unnoticed

2022-01-09 17:20 UTC, Nikolai-Isaev commented on services/src/main/scala/cromwell/pipeline/service/ProjectSearchFilterCleaner.scala
> +        val _ = system.scheduler.scheduleAtFixedRate(cleanInterval, cleanInterval, getFiltersCleanRun, executionContext)
fixed

2022-01-09 17:22 UTC, Nikolai-Isaev commented on services/src/main/scala/cromwell/pipeline/service/ProjectSearchFilterCleaner.scala
> +  def apply(projectSearchFilterService: ProjectSearchFilterService, miscConfig: MiscConfig, system: ActorSystem)(
fixed

2022-01-09 17:22 UTC, Nikolai-Isaev commented on services/src/main/scala/cromwell/pipeline/service/ProjectSearchFilterCleaner.scala
> +  def cleanExpiredFilters(): Unit
Fixed

2022-01-09 17:23 UTC, Nikolai-Isaev commented on utils/src/test/scala/cromwell/pipeline/utils/configs/ConfigJsonOpsTest.scala
> +       |      }
Oops, deleted

2022-01-09 17:23 UTC, Nikolai-Isaev commented on controllers/src/test/scala/cromwell/pipeline/controller/ProjectSearchControllerTest.scala
> +      "Return 404 if no projects was found" in {
Fixed

2022-01-09 17:25 UTC, Nikolai-Isaev commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dao/repository/ProjectSearchFilterRepository.scala
> +        database.run(projectSearchEntry.deleteOldSearches(usedLaterThan))
Fixed

2022-01-09 19:21 UTC, Nikolai-Isaev commented on services/src/test/scala/cromwell/pipeline/service/impls/ProjectSearchFilterServiceTestImpl.scala
> +    }
Tried to avoid testing with generation of a random id. Fixed

2022-01-10 08:47 UTC, Nikolai-Isaev commented on portal/src/it/resources/application.conf
> +misc {
Fixed

2022-01-12 09:05 UTC, myazinn approved these changes

2022-01-12 09:05 UTC, myazinn commented on utils/src/main/scala/cromwell/pipeline/utils/ApplicationConfig.scala
> +    val filtersDuration = _config.getConfig("filtersCleanup")
[minor]
```suggestion
    val filtersCleanup = _config.getConfig("filtersCleanup")
```

2022-01-12 11:56 UTC, Nikolai-Isaev commented on utils/src/main/scala/cromwell/pipeline/utils/ApplicationConfig.scala
> +    val filtersDuration = _config.getConfig("filtersCleanup")
Fixed

2022-01-19 11:12 UTC, GrigoriiBerezin approved these changes
Massive work

2022-01-20 13:29 UTC, merged