test: Removed ScalaFutures when ready, replaced with map
EpamLifeSciencesTeam/cmwl_pipeline pull request #234
Opened 2022-01-28 08:26 UTC by ForeverRainmaN

Removed ScalaFutures from places where it made sense

2022-01-28 10:34 UTC, myazinn requested changes

2022-01-28 10:34 UTC, myazinn commented on portal/src/it/scala/cromwell/pipeline/controller/AuthControllerItTest.scala
> +       userRepository.addUser(dummyUser).flatMap { _ =>
```suggestion
       userRepository.addUser(dummyUser).map { _ =>
```

2022-01-31 10:03 UTC, myazinn approved these changes

2022-02-01 09:57 UTC, GrigoriiBerezin approved these changes
Good job

2022-02-02 09:37 UTC, merged