Epmlstrcmw-157: delete and get endpoints for project file
EpamLifeSciencesTeam/cmwl_pipeline pull request #74
Opened 2020-05-27 08:52 UTC by IaroslavTavchenkov

2020-07-03 17:46 UTC, IaroslavTavchenkov commented on controllers/src/test/scala/cromwell/pipeline/controller/ProjectFileControllerTest.scala
> +    "get file" should {
Println doesn't work here :(

2020-07-04 13:17 UTC, GrigoriiBerezin commented on controllers/src/test/scala/cromwell/pipeline/controller/ProjectFileControllerTest.scala
> +    "get file" should {
https://github.com/IaroslavTavchenkov/cmwl_pipeline/pull/1

2020-07-08 10:12 UTC, GrigoriiBerezin requested changes
Great work, thanks. Just one moment to change.

2020-07-08 10:12 UTC, GrigoriiBerezin commented on controllers/src/main/scala/cromwell/pipeline/controller/ProjectFileController.scala
> +                println(version)
Must remove this

2020-07-09 10:15 UTC, IaroslavTavchenkov commented on controllers/src/main/scala/cromwell/pipeline/controller/ProjectFileController.scala
> +                println(version)
Thank you!)

2020-07-12 15:12 UTC, Dmitrii-Shevchenko approved these changes
Good job!

2020-07-20 23:42 UTC, iliaonishchenko requested changes
Thank you for you work!
There're several things we need to speak about...

2020-07-20 23:42 UTC, ilyaonishenko commented on controllers/src/main/scala/cromwell/pipeline/controller/ProjectFileController.scala
> +            parameter('projectId.as[String], 'path.as[String], 'version.as[String]) {
Didn't we agree that `version` query parameter should be optional? 
Also, this way of declaring parameters is deprecated in Akka-http now as far as I remember

2020-07-20 23:42 UTC, ilyaonishenko commented on controllers/src/main/scala/cromwell/pipeline/controller/ProjectFileController.scala
> +            parameter('projectId.as[String], 'path.as[String], 'branchName.as[String], 'commitMessage.as[String]) {
Why're we specifying such things as `branchName` and `commitMessage` ?
User doesn't know that we have git under the hood, so we should not disclosure internals for anyone.

2020-07-20 23:42 UTC, ilyaonishenko commented on controllers/src/main/scala/cromwell/pipeline/controller/ProjectFileController.scala
> +                      wdlService.deleteFile(project, Paths.get(path), branchName, commitMessage)
Why do we have this declaration?

2020-07-20 23:42 UTC, ilyaonishenko commented on controllers/src/test/scala/cromwell/pipeline/controller/ProjectFileControllerTest.scala
> +//import cromwell.pipeline.datastorage.dto.ProjectBuildConfigurationRequest.ProjectUpdateFileRequest
Why do we need commented line?

2020-07-20 23:42 UTC, ilyaonishenko commented on repositories/src/main/scala/cromwell/pipeline/datastorage/dto/Project.scala
> +}
Why do we need such complicated formatter? What is wrong with default?

2020-07-22 08:16 UTC, GrigoriiBerezin requested changes
Great, thank you. Agree with Ilya's comments, will approve after him

2020-09-08 09:11 UTC, closed without merging