EPMLSTRCMW-124: Move implicit formatters
EpamLifeSciencesTeam/cmwl_pipeline pull request #77
Opened 2020-06-08 14:01 UTC by AndreiMaksimenko

Custom exception handlers are already done with User micro types.
Implicit formatters for User, Project, and Auth was moved
to formatters package.

2020-06-08 18:54 UTC, GrigoriiBerezin approved these changes
Nothing to add. Good job

2020-06-09 09:51 UTC, IaroslavTavchenkov approved these changes
Well-done!

2020-06-10 09:25 UTC, OstapStrashevskii approved these changes
Nice work, all format implicits ordered in special places!

2020-06-18 10:40 UTC, iliaonishchenko approved these changes

2020-06-19 08:38 UTC, myazinn requested changes
What about formatters for our microtypes? I'm' talking about both the generic method `wrapperFormat` and his implementations like `userEmailFormat`.

2020-06-22 21:14 UTC, myazinn requested changes

2020-06-22 21:14 UTC, myazinn commented on repositories/src/main/scala/cromwell/pipeline/datastorage/formatters/UserFormatters.scala
> +  implicit lazy val userIdFormat: Format[UserId] = UserId.wrapperFormat
This is cheating :)
`wrapperFormat` must also be moved from `Wrapped` object into something like `WrappedFormatters` (maybe this is a bad name and there is a better one). You can put all formatters for these wrappers into that object.

2020-08-18 08:22 UTC, ilyaonishenko commented
I'm closing this MR because @OstapStrashevskii is working on this right now. 
And work is done in https://github.com/EpamLifeSciencesTeam/cmwl_pipeline/pull/90

2020-08-18 08:22 UTC, closed without merging